I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/locations.rpy", line 101, in script call
    call event_calls
  File "game/utilities.rpy", line 942, in script call
    call expression event_Girls[0].tag + "_Love"
  File "game/emma_scenes.rpy", line 1598, in script call
    call before_action(EmmaX, "sex", None)
  File "game/actions.rpy", line 177, in script
    label before_action(Girl, action, context):
Exception: Required parameter context has no value.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/locations.rpy", line 101, in script call
    call event_calls
  File "game/utilities.rpy", line 942, in script call
    call expression event_Girls[0].tag + "_Love"
  File "game/emma_scenes.rpy", line 1598, in script call
    call before_action(EmmaX, "sex", None)
  File "game/actions.rpy", line 177, in script
    label before_action(Girl, action, context):
  File "C:\Users\Quique\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 869, in execute
    values = apply_arguments(self.parameters, renpy.store._args, renpy.store._kwargs)
  File "C:\Users\Quique\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 159, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "C:\Users\Quique\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 123, in apply
    raise Exception("Required parameter %s has no value." % name)
Exception: Required parameter context has no value.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Rogue-Like 0.997f2
Wed Jun  1 04:21:49 2022
